
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    #defer-datasource-initialization: true
    hibernate: ddl-auto=create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
jwt:
  secret: EsegredinhoHem
